# Generated by Django 3.1.7 on 2021-03-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='randomcity',
            table='city',
        ),
    ]
